import os

TWITTER_CONSUMER_KEY = os.environ['TWITTER_CONSUMER_KEY']
TWITTER_CONSUMER_SECRET = os.environ['TWITTER_CONSUMER_SECRET']
TWITTER_APP_NAME = os.environ.get('TWITTER_APP_NAME')


print TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET
print TWITTER_APP_NAME
